-- ============================================================================
-- 03_load_staging.sql
-- Amazon Carbon Flux — 2005 Drought Analysis
--
-- Purpose: load the raw K34 text file into a "staging" table EXACTLY as-is.
--          No cleaning here — staging is just the raw landing zone. All
--          cleaning (numbers, -9999 -> NULL, dates) happens in the NEXT script.
--
-- Two real-world quirks of this file we handle here:
--   1. Column names clash when capitalisation is ignored (SQLite treats names
--      as case-insensitive), so auto-creation would fail. We define all columns
--      ourselves as TEXT and suffix the clashing ones with __2. The 8 columns
--      we actually use keep their exact original names.
--   2. Every data row ends with an extra empty field (a trailing tab), so rows
--      have 212 fields vs the header's 211. We add one throwaway trailing
--      column, "_trailing_ignore", to soak it up cleanly.
--
-- Run from the project root with:
--   sqlite3 data/flux.db < sql/03_load_staging.sql
-- ============================================================================

DROP TABLE IF EXISTS staging;

CREATE TABLE staging (
    "dateloc" TEXT,
    "Year_LBAMIP" TEXT,
    "DoY_LBAMIP" TEXT,
    "Hour_LBAMIP" TEXT,
    "Tair_LBAMIP" TEXT,
    "Qair_LBAMIP" TEXT,
    "Wind_LBAMIP" TEXT,
    "Rainf_LBAMIP" TEXT,
    "PSurf_LBAMIP" TEXT,
    "SWdown_LBAMIP" TEXT,
    "LWdown_LBAMIP" TEXT,
    "CO2air_LBAMIP" TEXT,
    "GF_Tair_LBAMIP" TEXT,
    "GF_Qair_LBAMIP" TEXT,
    "GF_Wind_LBAMIP" TEXT,
    "GF_Rainf_LBAMIP" TEXT,
    "GF_PSurf_LBAMIP" TEXT,
    "GF_SWdown_LBAMIP" TEXT,
    "GF_LWdown_LBAMIP" TEXT,
    "GF_CO2air_LBAMIP" TEXT,
    "ta" TEXT,
    "taed" TEXT,
    "wd" TEXT,
    "wded" TEXT,
    "pressed" TEXT,
    "press" TEXT,
    "rg" TEXT,
    "rr" TEXT,
    "par" TEXT,
    "rpar" TEXT,
    "Rn" TEXT,
    "FG" TEXT,
    "wsed" TEXT,
    "ws" TEXT,
    "H" TEXT,
    "Hraw" TEXT,
    "LE" TEXT,
    "Leraw" TEXT,
    "Fc" TEXT,
    "Fcraw" TEXT,
    "co2" TEXT,
    "sco2" TEXT,
    "NEE" TEXT,
    "NEEf" TEXT,
    "mrs" TEXT,
    "ust" TEXT,
    "rh" TEXT,
    "prec" TEXT,
    "h2o" TEXT,
    "Fh2o" TEXT,
    "U" TEXT,
    "Ued" TEXT,
    "V" TEXT,
    "Ved" TEXT,
    "ee" TEXT,
    "ees" TEXT,
    "dpt" TEXT,
    "tsavg" TEXT,
    "eqtemp" TEXT,
    "abshu" TEXT,
    "slopee" TEXT,
    "radtop" TEXT,
    "rgs" TEXT,
    "rgsout" TEXT,
    "rgl" TEXT,
    "rglout" TEXT,
    "stdW" TEXT,
    "ang" TEXT,
    "Tau" TEXT,
    "zl" TEXT,
    "tprof1" TEXT,
    "tprof2" TEXT,
    "tprof3" TEXT,
    "tprof4" TEXT,
    "tprof5" TEXT,
    "tprof6" TEXT,
    "tprof7" TEXT,
    "tprof8" TEXT,
    "tprof9" TEXT,
    "tprof10" TEXT,
    "avgprofT" TEXT,
    "msoil1" TEXT,
    "msoil2" TEXT,
    "msoil3" TEXT,
    "msoil4" TEXT,
    "msoil5" TEXT,
    "msoil6" TEXT,
    "msoil7" TEXT,
    "msoil8" TEXT,
    "msoil9" TEXT,
    "msoil10" TEXT,
    "totalteta" TEXT,
    "pco2_1" TEXT,
    "pco2_2" TEXT,
    "pco2_3" TEXT,
    "pco2_4" TEXT,
    "pco2_5" TEXT,
    "pco2_6" TEXT,
    "pco2_7" TEXT,
    "pco2_8" TEXT,
    "pco2_9" TEXT,
    "pco2_10" TEXT,
    "avgsto" TEXT,
    "h2o_1" TEXT,
    "h2o_2" TEXT,
    "h2o_3" TEXT,
    "h2o_4" TEXT,
    "h2o_5" TEXT,
    "h2o_6" TEXT,
    "h2o_7" TEXT,
    "h2o_8" TEXT,
    "h2o_9" TEXT,
    "h2o_10" TEXT,
    "avgprofW" TEXT,
    "Wind1" TEXT,
    "Wind2" TEXT,
    "Wind3" TEXT,
    "Wind4" TEXT,
    "Wind5" TEXT,
    "Wavg" TEXT,
    "tsoil1" TEXT,
    "tsoil2" TEXT,
    "tsoil3" TEXT,
    "tsoil4" TEXT,
    "tsoil5" TEXT,
    "So" TEXT,
    "Re_5day" TEXT,
    "Re_5day_ust" TEXT,
    "Re_5day_sco2" TEXT,
    "Re_5day_sco2_ust" TEXT,
    "Re_5day_ust_min" TEXT,
    "Re_5day_ust_max" TEXT,
    "Re_5day_sco2_ust_min" TEXT,
    "Re_5day_sco2_ust_max" TEXT,
    "Re_fourier_model" TEXT,
    "Re_fourier_ust_model" TEXT,
    "Re_fourier_sco2_model" TEXT,
    "Re_fourier_sco2_ust_model" TEXT,
    "Re_fourier_ust_min_model" TEXT,
    "Re_fourier_ust_max_model" TEXT,
    "Re_fourier_sco2_ust_min_model" TEXT,
    "Re_fourier_sco2_ust_max_model" TEXT,
    "NEE_night" TEXT,
    "Fc_night" TEXT,
    "NEE_night_ust" TEXT,
    "Fc_night_ust" TEXT,
    "Re_5day_ust_Sco2_LUT" TEXT,
    "Re_5day_ust_Sco2_IwataLIN" TEXT,
    "Re_5day_ust_Sco2_IwataLN" TEXT,
    "Re_5day_ust_Sco2_IwataPOL" TEXT,
    "Re_5day_ust_Sco2_EC" TEXT,
    "Re_5day_ust_Sco2_DIEL" TEXT,
    "NEEnogap_5day_ust_Sco2_LUT" TEXT,
    "NEEnogap_5day_ust_Sco2_IwataLIN" TEXT,
    "NEEnogap_5day_ust_Sco2_IwataLN" TEXT,
    "NEEnogap_5day_ust_Sco2_IwataPOL" TEXT,
    "NEEnogap_5day_ust_Sco2_EC" TEXT,
    "NEEnogap_5day_ust_Sco2_DIEL" TEXT,
    "GEP_5day_sco2_ust" TEXT,
    "GEP_5day_sco2_ust_max" TEXT,
    "GEP_5day_sco2_ust_min" TEXT,
    "GEP_5day_ust" TEXT,
    "GEP_5day_ust_max" TEXT,
    "GEP_5day_ust_min" TEXT,
    "GEP_5day_sco2" TEXT,
    "GEP_5day" TEXT,
    "GEP_5day_sco2_ust_hyperbola" TEXT,
    "GEP_5day_sco2_ust_hyperbola__2" TEXT,
    "GEP_5day_ust_hyperbola" TEXT,
    "GEP_5day_sco2_hyperbola" TEXT,
    "GEP_5day_hyperbola" TEXT,
    "NEE_spike5_free" TEXT,
    "NEEnogap_5day_sco2_ust" TEXT,
    "NEEnogap_5day_ust" TEXT,
    "NEEnogap_5day_sco2" TEXT,
    "NEEnogap_5day" TEXT,
    "Sco2_LUT" TEXT,
    "Sco2_IwataLIN" TEXT,
    "Sco2_IwataLN" TEXT,
    "Sco2_IwataPOL" TEXT,
    "Sco2_EC" TEXT,
    "Sco2_DIEL" TEXT,
    "Fc_spike7_free" TEXT,
    "Sco2__2" TEXT,
    "GEP_5day_ust_Sco2_LUT" TEXT,
    "GEP_5day_ust_Sco2_IwataLIN" TEXT,
    "GEP_5day_ust_Sco2_IwataLN" TEXT,
    "GEP_5day_ust_Sco2_IwataPOL" TEXT,
    "GEP_5day_ust_Sco2_EC" TEXT,
    "GEP_5day_ust_Sco2_DIEL" TEXT,
    "GEP_5day_ust_Sco2_UST" TEXT,
    "GEP_5day_ust_Sco2_REG" TEXT,
    "GEP_model" TEXT,
    "GEPmodel_ust_max" TEXT,
    "GEPmodel_ust_min" TEXT,
    "Re_model" TEXT,
    "Remodel_ust_max" TEXT,
    "Remodel_ust_min" TEXT,
    "Sco2_model" TEXT,
    "NEE_model_ust_max" TEXT,
    "NEE_model_ust_min" TEXT,
    "NEE_model" TEXT,
    "par_fill" TEXT,
    "Pc" TEXT,
    "Pc_GEPfill" TEXT,
    "Pc_AM" TEXT,
    "Pc_PM" TEXT,
    "Pcatmed.VPD" TEXT,
    "PcatlowVPD" TEXT,
    "PcathighVPDvalues" TEXT,
    "VPD" TEXT,
    "_trailing_ignore" TEXT   -- absorbs the stray empty 212th field
);

-- .mode tabs       -> the file is TAB-separated
-- .import --skip 2 -> skip the 2 header rows (names + units); load only data
.mode tabs
.import --skip 2 data/K34day_CfluxBF.txt staging
